// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REDACTED_GOOGLE_API_KEY',
    appId: '1:290764760328:web:6e0f2ff6ccf90f534978bd',
    messagingSenderId: '290764760328',
    projectId: 'pharma-sfa',
    authDomain: 'pharma-sfa.firebaseapp.com',
    storageBucket: 'pharma-sfa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REDACTED_GOOGLE_API_KEY',
    appId: '1:290764760328:android:6b9eb469a36250e44978bd',
    messagingSenderId: '290764760328',
    projectId: 'pharma-sfa',
    storageBucket: 'pharma-sfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REDACTED_GOOGLE_API_KEY',
    appId: '1:290764760328:ios:423ab9d7a0d6c5244978bd',
    messagingSenderId: '290764760328',
    projectId: 'pharma-sfa',
    storageBucket: 'pharma-sfa.firebasestorage.app',
    iosBundleId: 'com.example.microPharma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REDACTED_GOOGLE_API_KEY',
    appId: '1:290764760328:ios:423ab9d7a0d6c5244978bd',
    messagingSenderId: '290764760328',
    projectId: 'pharma-sfa',
    storageBucket: 'pharma-sfa.firebasestorage.app',
    iosBundleId: 'com.example.microPharma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REDACTED_GOOGLE_API_KEY',
    appId: '1:290764760328:web:a8488a81ff1c4d6c4978bd',
    messagingSenderId: '290764760328',
    projectId: 'pharma-sfa',
    authDomain: 'pharma-sfa.firebaseapp.com',
    storageBucket: 'pharma-sfa.firebasestorage.app',
  );
}
